# Source: https://www.geekytidbits.com/github-actions-version-and-release-to-npm/
name: Bump minor version of before new release/deploy
on:
  push:
    branches:
      - master
    paths:
      - "minor.js"

jobs:
  release-new-minor-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release author
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          # GitHub automatically creates a GITHUB_TOKEN secret (use it to authenticate in a workflow run)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Release minor version
        run: |
          export GITHUB_ACTOR=$GITHUB_ACTOR
          npm version minor --force -m "New minor release by $GITHUB_ACTOR: v%s"
      - name: Push release commit and tag to GitHub
        run: |
          git push gh-origin HEAD:master
          git push gh-origin --tags
