# Source: https://www.geekytidbits.com/github-actions-version-and-release-to-npm/
name: Bump patch version of before new release/deploy
on:
  # pull_request:
  #   branches:
  #     - master
  #   types: [closed]
  pull_request:
    types: [opened]
    paths:
      - "**"
      - "!minor.js"
      - "!major.js"

jobs:
  createPullRequest:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "Author: $GITHUB_ACTOR"
          echo "Repository: ${GITHUB_ACTOR}:---github.com/${GITHUB_REPOSITORY}.git"

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Release patch version
        working-directory: ./subfolder
        run: |
          export GITHUB_ACTOR=$GITHUB_ACTOR
          export REPO=https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm version patch --force
          cd ..
          git add .
          git commit -m "[Approved] New patch release by $GITHUB_ACTOR in $REPO: v%s"
          git push
