# Source: https://www.geekytidbits.com/github-actions-version-and-release-to-npm/
name: Bump patch version of before new release/deploy
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!minor.js"
      - "!major.js"

jobs:
  release-new-patch-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release author
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          echo "Author: $GITHUB_ACTOR"
          echo "Repository: ${GITHUB_ACTOR}:---github.com/${GITHUB_REPOSITORY}.git"
        env:
          # GitHub automatically creates a GITHUB_TOKEN secret (use it to authenticate in a workflow run)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Release patch version with commit to GitHub
        working-directory: ./subfolder
        run: |
          export GITHUB_ACTOR=$GITHUB_ACTOR
          export REPO=https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm version patch --force
          cd ..
          git add .
          git commit -m "New patch release by $GITHUB_ACTOR in $REPO: v%s"
